### ISSUE TITLE
low recall accuracy

### ISSUE THREAD

**Issue by yuzhichang** [ZJULearning/nsg#4]
[test_nsg_optimized_search_recall.cpp.tar.gz](https://github.com/ZJULearning/nsg/files/1817758/test_nsg_optimized_search_recall.cpp.tar.gz)

I'm trying to reproduce your benchmark on sift1M dataset. I adjusted the parameters of kNN graph and search. However I failed to improve the recall accuracy to 0.993。

[root@cdsl-gpu-a07 tests]# ./test_nndescent ../../sift/sift_base.fvecs sift.50NN.graph 50 70 10 10 100
data dimension: 128
recall : 0.0003
iter: 0
recall : 0.002
iter: 1
recall : 0.0221
iter: 2
recall : 0.1011
iter: 3
recall : 0.2899
iter: 4
recall : 0.511
iter: 5
recall : 0.6378
iter: 6
recall : 0.6833
iter: 7
recall : 0.6955
iter: 8
recall : 0.6987
iter: 9
1000000
Time cost: 40.4963

[root@cdsl-gpu-a07 tests]# ./test_nsg_index ../../sift/sift_base.fvecs ../../efanna_graph/tests/sift.50NN.graph 256 100 sift.50NN.nsg
100:34:2:0
indexing time: 102.874

[root@cdsl-gpu-a07 tests]# ./test_nsg_optimized_search_recall ../../sift/sift_base.fvecs ../../sift/sift_query.fvecs sift.50NN.nsg 100 1 ../../sift/sift_groundtruth.ivecs 
34
search time: 9.37674
Compute recalls
R@1 = 0.9906
R@10 = 0.9906
R@100 = 0.9906

The attached is code of test_nsg_optimized_search_recall, which's based on test_nsg_optimized_search.cpp and (faiss repo) demo_sift1M.cpp.

As a reference, the nmslib HNSW sample code gived recall accuracy 0.999 on sift1M with 500 queries.
What I need is exact 1NN search on big dataset. And it's fine to comprise on R@1 and performance a bit. 

Could you help me?
Thanks!

**Comment by CongFu92** [comment]
I cannot reproduce your results. It seems normal here on my computer.
I tried the 50nn graph as you do, below are the results.
./tests/test_nndescent ../sift/sift_base.fvecs ../sift/sift_50.nndgraph 50 70 10 10 100
./tests/test_nsg_index ../sift/sift_base.fvecs ../sift/sift_50.nndgraph 300 50 ../sift/sift_50.nsg

./tests/test_nsg_optimized_search ../sift/sift_base.fvecs ../sift/sift_query.fvecs ../sift/sift_50.nsg 100 1 ../sift/sift.1nn
search time: 3.23324
R@1:
./validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 1
res dim : 1 gt dim : 100
0.9905
R@10:
./validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 10
res dim : 1 gt dim : 100
1.00
R@100:
/validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 100
res dim : 1 gt dim : 100
1.00

more detailed report and our evaluation code have been sent to your email.

you may try the same 10,000 queries of SIFT1M dataset on HNSW rather than 500 for comparison. 
Because we don't know which 500 queries you were using.

**Comment by CongFu92** [comment]
L=1000
./tests/test_nsg_optimized_search ../sift/sift_base.fvecs ../sift/sift_query.fvecs ../sift/sift_50.nsg 1000 1 ../sift/sift.1nn
search time: 25.4909
R@1:
./validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 1
res dim : 1 gt dim : 100
0.9944
R@10:
./validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 10
res dim : 1 gt dim : 100
1.00
R@100:
/validate_K sift/sift.1nn sift/sift_groundtruth.ivecs 100
res dim : 1 gt dim : 100
1.00
